/**
 * P109-C：系统提示的两条守卫。
 *
 * 为什么专门测提示词：旧提示是一整块硬编码长字符串，里面点名的 `read_appearance`
 * **根本不是一支工具**（真名 `theme_read`）——弱模型第一轮就撞 `unknown_tool`，
 * 而"界面创造"档压根没发外观工具，提示还在教怎么用它们。这类漂移没有门禁就会一直长回来，
 * 所以钉成测试（手法与 `bootOverrides.test.ts` 读源码比对同一类：比的是"两处写法有没有漂"）。
 */
import { expect, it } from "vitest";
// 变量说明符：src 的 tsconfig 不挂 @types/node，写 `node:fs` 字面量会被 tsc 判"找不到模块"
const fsSpec = "node:fs";
const urlSpec = "node:url";
const { readFileSync } = (await import(fsSpec)) as unknown as { readFileSync: (p: string, enc?: string) => string };
const { fileURLToPath } = (await import(urlSpec)) as unknown as { fileURLToPath: (u: string | URL) => string };

const read = (f: string) => readFileSync(fileURLToPath(new URL(f, import.meta.url)), "utf8");
const loopSrc = read("./loop.ts");

/** 宿主工具的真名：从各 entry 表里抠 `name: "…"` 字面量（注册表要求这个名字合法） */
function registryNames(): Set<string> {
  // 与 hostEntries.ts 那七组一一对应（P133-B2 之后新增 `subagent.ts`：新工具组文件必须同时进这张表，
  // 否则这条守卫会把"提示点了一支真存在的工具"误判成死引用——本批就是被它自己抓到的）
  const files = ["./localEntries.ts", "./uiTools.ts", "./settingsTools.ts", "./appearanceTools.ts",
    "./generalTools.ts", "./marketTools.ts", "./pluginTools.ts", "./subagent.ts"];
  const names = new Set<string>();
  for (const f of files) {
    for (const m of read(f).matchAll(/\bname:\s*"([a-z][a-z0-9_]{2,39})"/g)) names.add(m[1]);
  }
  return names;
}

/** 把 loop.ts 里 `["<tool>", " 文案"]` 形状的分片键抠出来 */
function fragmentKeys(): string[] {
  const block = loopSrc.slice(loopSrc.indexOf("const PROMPT_FRAGMENTS"), loopSrc.indexOf("export function buildSystemPrompt"));
  return [...block.matchAll(/^\s*\["([a-z][a-z0-9_]+)"/gm)].map((m) => m[1]);
}

it("提示里点名的工具必须真的存在于注册表（read_appearance 那类死引用不许长回来）", () => {
  const real = registryNames();
  expect(real.size, "一个工具名都没抠到 —— 表结构变了要同步改这条").toBeGreaterThan(20);
  // 抠到的分片键本身也要非空：键的形状一改（比如换成对象），这条守卫会静默变成"永远通过"
  const keys = fragmentKeys();
  expect(keys.length, "一条分片键都没抠到 —— PROMPT_FRAGMENTS 的写法变了，这条守卫要跟着改").toBeGreaterThanOrEqual(4);
  const ghost = keys.filter((k) => !real.has(k));
  expect(ghost, `提示分片点了不存在的工具：${ghost.join(", ")}`).toEqual([]);
});

/**
 * P133-E：恒发那一段。它讲的两件事在回执里早就写了、提示面一直没有配套，
 * 于是现场变成"用户点了拒绝，模型第二轮把同参数又发一遍"（P133-C2 实录）。
 * 恒发段的键是 `*`，上面那条工具名守卫刻意不看它——它不许点任何工具名，
 * 否则"没发出去的工具也在提示里教怎么用"这个老毛病会从这里长回来。
 */
it("P133-E：拒绝语义与生成物口径恒发，且不含任何工具名", async () => {
  const { buildSystemPrompt } = await import("./loop");
  const bare = buildSystemPrompt(new Set(["app_read"]));
  expect(bare).toContain("approval_rejected");
  expect(bare).toContain("approval_expired");
  expect(bare).toContain("do not resend the same arguments");
  expect(bare).toContain("generated by a command");
  // 恒发段一旦点了工具名，低档位就会撞 unknown_tool。这里拿"只发了一支只读工具"的渲染结果
  // 来查：基础段本来就不许有工具名（上一条守卫管着），所以多出来的名字只可能来自恒发段。
  const named = [...bare.matchAll(/\b(?:read|save|theme|style|settings|app|ui|fs|list|enable|rollback|plot|image|web|shell|task|run|propose|layout|chrome|session)_[a-z0-9_]+\b/g)].map((m) => m[0]);
  expect(named, `恒发段点了工具名：${named.join(", ")}`).toEqual([]);
});

it("基础提示里不许出现任何 `xxx_yyy` 形式的工具名（要提工具就走进分片段）", () => {
  const base = /const PROMPT_BASE = "([\s\S]*?)";\n/.exec(loopSrc)?.[1] ?? "";
  expect(base.length).toBeGreaterThan(200);
  const named = [...base.matchAll(/\b(?:read|save|theme|style|settings|app|ui|fs|list|enable|rollback|plot|image|web|shell|task|run|propose|layout|chrome|session)_[a-z0-9_]+\b/g)].map((m) => m[0]);
  expect(named, `基础段里点名了工具，可它不分档位：${named.join(", ")}`).toEqual([]);
});

it("死引用 read_appearance 不在发给模型的任何一段提示里（真名是 theme_read）", async () => {
  // 判据落在**渲染结果**上而不是源码上：源码里作为历史说明提一次它是允许的（注释里就在讲这件事），
  // 真正不能容忍的是模型照着它去调一支不存在的工具。
  const { buildSystemPrompt } = await import("./loop");
  const all = buildSystemPrompt(new Set(["theme_read", "save_plugin", "task_plan", "theme_patch", "theme_preset", "save_theme_extension", "image_swatch"]));
  expect(all.length).toBeGreaterThan(400);
  expect(all).not.toContain("read_appearance");
});

it("外观那段的可见性跟着工具走：没发 theme_read 就不教怎么用", async () => {
  const { buildSystemPrompt } = await import("./loop");
  const withTheme = buildSystemPrompt(new Set(["theme_read", "save_plugin"]));
  const bare = buildSystemPrompt(new Set(["app_read"]));
  expect(withTheme).toContain("call theme_read first");
  expect(withTheme).toContain("save_plugin with enable:true");
  expect(bare, "工具没发出去，提示里却还在教怎么用 ⇒ 模型会去撞 unknown_tool").not.toContain("Appearance edits");
  expect(bare).not.toContain("save_plugin");
  // 基础段与可见性无关，永远在
  expect(bare).toContain("No tool call means task termination");
});
